const STRING_SURVIVOR_DIE                  = " was infected by "; // #tf_zi_ui_survivor_die
const STRING_UI_CHAT_INFECT_MSG            = "\x07FF3F3F%s\x07FBECCB was \x0722FF22infected\x07FBECCB by \x0738F3AB%s!"// #tf_zi_ui_infect_msg
const STRING_UI_CHAT_INFECT_SOLO_MSG       = "\x07FF3F3F%s\x07FBECCB was \x0722FF22infected!" // #tf_zi_ui_infect_solo_msg
const STRING_UI_CHAT_LAST_SURV_YELLOW      = "\x07FBECCB%d SURVIVORS REMAIN! They now have \x07FFD700%s!" // #tf_zi_ui_last_survivor_minicrit
const STRING_UI_CHAT_LAST_SURV_GREEN       = "\x07FF3F3F%s\x07FBECCB IS THE LAST SURVIVOR! They now have \x0716FD1D%s!" // #tf_zi_ui_last_survivor_crit
const STRING_UI_CRITS                      = "CRITICAL HITS" // #tf_zi_ui_crits
const STRING_UI_MINI_CRITS                 = "MINI-CRITS" // #tf_zi_ui_minicrits
const STRING_UI_CHAT_FIRST_WAVE_MSG_PLURAL = " have become \x0722FF22INFECTED!"; // #tf_zi_ui_first_wave_msg_plural
const STRING_UI_PASSIVE                    = "#tf_zi_ui_passive"
const STRING_UI_CASTING                    = "#tf_zi_ui_casting"
const STRING_UI_READY                      = "#tf_zi_ui_ready"
const STRING_UI_READY_IN                   = "#tf_zi_ui_ready_in"
const STRING_UI_CHAT_FIRST_WAVE_MSG        = " has become \x0722FF22INFECTED!";   // #tf_zi_ui_first_wave_msg
const STRING_UI_AND                        = "and";
const STRING_UI_ZOMBIE_INSTRUCTION         = "#tf_zi_ui_zombie_instruction"
const STRING_UI_ZOMBIE_INSTRUCTION_PASSIVE = "#tf_zi_ui_zombie_instruction_passive"
const STRING_UI_TEAM_BLUE                  = "#tf_zi_team_blue";
const STRING_UI_TEAM_RED                   = "#tf_zi_team_red";

const SCOUT_PASSIVE_NAME                   = "#tf_zi_scout_passive_name"
const PYRO_PASSIVE_NAME                    = "#tf_zi_pyro_passive_name"
const HEAVY_PASSIVE_NAME                   = "#tf_zi_heavy_passive_name"
const MEDIC_PASSIVE_NAME                   = "#tf_zi_medic_passive_name"
const ENGIE_EMP_NAME                       = "#tf_zi_engie_emp_name"
const DEMO_CHARGE_NAME                     = "#tf_zi_demo_charge_name"
const MEDIC_HEAL_NAME                      = "#tf_zi_medic_heal_name"
const SNIPER_SPIT_NAME                     = "#tf_zi_sniper_spit_name"
const SOLDIER_POUNCE_NAME                  = "#tf_zi_soldier_pounce_name"
const SPY_REVEAL_NAME                      = "#tf_zi_spy_reveal_name"
const PYRO_BLAST_NAME                      = "#tf_zi_pyro_blast_name"

const SCOUT_PASSIVE_DESC                   = "";
const PYRO_PASSIVE_DESC                    = "";
const HEAVY_PASSIVE_DESC                   = "";
const ENGIE_EMP_DESC                       = "";
const DEMO_CHARGE_DESC                     = "";
const MEDIC_HEAL_DESC                      = "";
const SNIPER_SPIT_DESC                     = "";
const SOLDIER_POUNCE_DESC                  = "";
const SPY_REVEAL_DESC                      = "";
const MEDIC_HEAL_DESC                      = "";
